name: Second Workflow
on: 
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: print helloworld
        run: echo "hello world!"
      - name: Multiple commands
        run: |
            date
            pwd
            whoami
            hostname
            
